# configure the firewall workers access (1/2)
- name: configure the firewall workers access (1/2)
  become: yes    
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    zone: public
  with_items:        
    - "{{ workers_firewall_ports }}"

# reload firewalld service (2/2)
#- name: reload 'firewalld' service (2/2)
#  become: yes
#  systemd:
#    name: firewalld
#    state: reloaded  

# Reload 'firewalld' service (2/2)
- name: reload firewall service (2/2)
  become: yes
  command: firewall-cmd --reload    