# join the cluster with join_command in master node
- name: join cluster
  become: yes
  shell: "{{ hostvars['master.local'].join_command }} >> node_joined.txt"
  args:
    chdir: $HOME
    creates: node_joined.txt     