# Join the cluster with join_command in master
- name: join cluster
  shell: "{{ hostvars['master.local'].join_command }} >> node_joined.txt"
  args:
    chdir: $HOME
    creates: node_joined.txt     