---

# Set Timezone configuration to Europe/Madrid
- name: set timezone
  timezone:
    name: "{{ time_zone }}"
  become: yes  

# Install the latest version of Chrony package
- name: install packages
  dnf:
    name: "{{ time_rpms }}"
    state: latest
  become: yes    

# Make sure a chrony service unit is enabled and running
#- name: enable chrony service
#  service:
#    name: chronyd
#    state: started
#    enabled: yes
#  become: yes

# Enable chronyd service
- name: enable chronyd
  become: yes
  command: /usr/bin/systemctl enable chronyd

# Start chronyd service
- name: start chronyd 
  become: yes
  command: /usr/bin/systemctl start chronyd  


# Enable NTP (Network Time Protocol) to sync the system date/hour
- name: enable ntp
  become: yes
  command: /usr/bin/timedatectl set-ntp true


