---

# Set Timezone configuration to Europe/Madrid
- name: set timezone
  timezone:
    name: "{{ time_zone }}"
  become: yes  

# Install the latest version of Chrony package
- name: install packages
  dnf:
    name: "{{ time_rpms }}"
    state: latest
  become: yes    

# Make sure a chrony service unit is enabled and running
- name: enable chrony service
  service:
    name: chronyd
    state: started
  become: yes
  become_method: su

# Enable NTP (Network Time Protocol) to sync the system date/hour
- name: enable ntp
  become: yes
  command: /usr/bin/timedatectl set-ntp true


