---

# Make sure a chrony service unit is enabled and running
- name: enable services
  become: yes
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - "{{ nfs_services }}"
