---

# Enable nfs-server service
- name: enable nfs-server
  become: yes
  command: /usr/bin/systemctl enable nfs-server

# Start nfs-server service
- name: start nfs-server
  become: yes
  command: /usr/bin/systemctl start nfs-server    
