---

# Make sure a 'firewalld' service unit is enabled and running
- name: make sure a firewall service is enabled and running
  systemd:
    name: firewalld
    state: started        
    enabled: yes
  become: yes

# Activate transparent masquerading
- name: activate transparent masquerading
  command: /usr/sbin/modprobe br_netfilter
  become: yes

# Add permanent masquerade
- name: add permanent masquerade
  firewalld:
    masquerade: 'yes'
    state: enabled        
    permanent: yes
  become: yes  

# Reload 'firewalld' service
- name: reload firewall service
  systemd:
    name: firewalld
    state: reloaded
  become: yes

# Copy 'k8s.conf' file to '/etc/sysctl.d/k8s.conf'
- name: copy 'k8s.conf' file to '/etc/sysctl.d/k8s.conf'
  copy:
    src: "{{ item.file }}"
    dest: "{{ item.path }}"
  with_items:
    - { file: 'k8s.conf', path: '/etc/sysctl.d/k8s.conf'}
  become: yes    

# Reload settings from all system configuration files
- name: Reload settings from all system configuration files
  command: /usr/sbin/sysctl --system
  become: yes