- name: create a directory if it does not exist
  file:
    path: /apps/jenkins
    state: directory
    mode: '0755'

- name: copy jenkins file app
  copy:
    src: "{{ item.file }}"
    dest: "{{ item.path }}"
  with_items:
    - { file: 'jenkins-app.yaml', path: '$HOME/apps/jenkins/jenkins-app.yaml'}
  become: yes    

- name: install jenkins
  shell: kubectl apply -f $HOME/apps/jenkins/jenkins-app.yaml

