- name: create a directory if it does not exist
  file:
    path: /home/kubeadmin/apps/jenkins
    state: directory
    mode: '0755'
  become: yes

- name: copy jenkins file app
  copy:
    src: "{{ item.file }}"
    dest: "{{ item.path }}"
  with_items:
    - { file: 'jenkins-app.yaml', path: '/home/kubeadmin/apps/jenkins/jenkins-app.yaml'}
  become: yes

- name: install jenkins
  shell: kubectl apply -f $HOME/apps/jenkins/jenkins-app.yaml
  become: yes  

