---

# VG (volume group)
vg_name: 'data_vg' # Name of Volume group
pvs_name: '/dev/sdb' # Physical Volume created using partition eg (/dev/sdb1 or /dev/sdc1)
physical_extent_size: '8' # The size of the physical extent. eg (8MB, 32MB,...)

# LV (logical volume)
lv_name: 'nfs_lv' # Name of Logical Volume
lv_size: '100%FREE' # The size of the logical volume, according to lvcreate(8)

# Type of filesystem 
file_system: 'xfs' # What type of filesystem it can be ext3, ext4 or xfs etc.

# Mount the created filesystem
mount_point: '/srv/nfs'

# NFS packages
nfs_rpms: ['nfs-utils','net-tools']
# NFS services
nfs_services: ['nfs-server']
# FNS firewall
nfs_firewall: ['nfs','rpc-bind','mountd']