---

# VG (volume group)
vg_name: 'data_vg' # Name of volume group
# local.lab /dev/sdb in local
pvs_name: '/dev/sdb' # Physical volume created using partition. eg (/dev/sdb1 or /dev/sdc1)
# azure.lab /dev/sdc in azure
#pvs_name: '/dev/sdc' # Physical volume created using partition. eg (/dev/sdb1 or /dev/sdc1)
physical_extent_size: '8' # The size of the physical extent. eg (8MB, 32MB,...)

# LV (logical volume)
lv_name: 'nfs_lv' # Name of logical volume
lv_size: '100%VG' # Resize the logical volume to % of VG

# Type of filesystem 
file_system: 'xfs' # Type of filesystem (ext3, ext4, xfs, etc)

# Mount the created filesystem
mount_point: '/srv/nfs'

# NFS packages
nfs_rpms: ['nfs-utils','net-tools']
# NFS services
nfs_services: ['nfs-server']
# FNS firewall
nfs_firewall: ['nfs','rpc-bind','mountd'] 