---

# Make sure a kubernetes service is enabled and running
#- name: enable services
#  systemd:
#    name: "{{ item }}"
#    state: started
#    enabled: yes
#  become: yes
#  with_items:
#    - "{{ kubernetes_services }}"

# Enable kubelet service
- name: Enable kubelet service
  become: yes
  command: systemctl enable kubelet

# Start kubelet service
- name: Start kubelet service
  become: yes
  command: systemctl start kubelet