---

# Make sure a kubernetes service is enabled and running
- name: enable services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  become: yes
  with_items:
    - "{{ kubernetes_services }}"