---

# We discourage SELinux since we are not going to use it with kubernetes
- name: Install the python3-libselinux package
  dnf:
    name: python3-libselinux
    state: latest
  become: yes      

- name: Disable SELinux
  selinux: 
    state: disabled
  become: yes
