---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  namespace: wordpress
  labels:
    app: wordpress
    type: frontend
  annotations:
      haproxy.org/path-rewrite: "/"
spec:
  rules:
  - host: wp.20.71.93.216.nip.io
    http:
      paths:
      - path: /
        pathType: "Prefix"
        backend:
          service:
            name: wordpress-service
            port:
              number: 80          