# Apply and Verify
# kubectl apply -k ./
# kubectl get pods --namespace=wordpress -o wide
# kubectl get deploy,service,pods -n wordpress
# sudo kubectl get events --all-namespaces  --sort-by='.metadata.creationTimestamp'
resources:
  - wordpress-ns.yaml  
  - wordpress-pv.yaml  
  - wordpress-pvc.yaml
  - wordpress-deployment.yaml  