apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: wordpress-volumes
  labels:
    app: wordpress-volumes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-volumes
  template:
    metadata:
      labels:
        app: wordpress-volumes
    spec:
      containers:
      - name: wordpress-volumes
        image: mysql:5.6
        ports:
        - containerPort: 3306
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password

---
apiVersion: v1
kind: Service
metadata:
    name: mysql-service
    namespace: wordpress-volumes
spec:
    selector:
      app: wordpress-volumes
    ports:
    - name: http
      protocol: TCP
      port: 3306
      targetPort: 3306