apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: wordpress-volumes
  labels:
    app: wordpress-volumes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-volumes
  template:
    metadata:
      labels:
        app: wordpress-volumes
    spec:
      containers:
      - name: wordpress-volumes
        image: wordpress:5.2
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80 
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-service
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password

---
apiVersion: v1
kind: Service
metadata:
    name: wordpress-service
    namespace: wordpress-volumes
spec:
    selector:
      app: wordpress-volumes
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80