---

## INSTALL DOCKER ##

# install the latest version of docker (1/2)
- name: install the latest version of docker (1/2)
  dnf:
    enablerepo: "{{ docker_repo }}"
    name: "{{ docker_rpms }}"
    state: present
  become: yes

# make sure a docker service is enabled and running (2/2)
- name: make sure a docker service is enabled and running (2/2)
  systemd:
    name: docker
    state: started
    enabled: yes
    masked: no
  become: yes