---

## INSTALL DOCKER ##

# add docker repo (1/3)
#- name: add docker repo (1/3)
#  command: "/usr/bin/dnf config-manager --add-repo={{ docker_repo }}"
#  become: yes

# install the latest version of docker (2/3)
- name: install the latest version of docker (2/3)
  dnf:
    enablerepo: "{{ docker_repo }}"
    name: "{{ docker_rpms }}"
    state: present
  become: yes

# make sure a docker service is enabled and running (3/3)
- name: make sure a docker service is enabled and running (3/3)
  systemd:
    name: docker
    state: started
    enabled: yes
    masked: no
  become: yes