---

## INSTALL DOCKER ##

#- name: Set the stable docker repository
#  dnf: 
#    enablerepo: "{{ docker_repo }}"
#    state: present
#    update_cache: yes    
#  become: yes

# Add docker repo
- name: Add docker repo
  become: yes
  command: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

# add docker repo (1/2)
#- name: add docker repo (1/2)
#  copy:
#    src: "{{ item.file }}"
#    dest: "{{ item.path }}"
#  with_items:
#    - { file: 'docker.repo', path: '/etc/yum.repos.d/docker.repo'}
#  become: yes  

- name: Install Docker (2/2)
  dnf:
    #enablerepo: https://download.docker.com/linux/centos/docker-ce.repo
    update_cache: yes
    name: docker-ce
    state: present
  become: yes    

# install the latest version of docker (1/2)
#- name: install the latest version of docker (1/2)
#  dnf:
#    enablerepo: "{{ docker_repo }}"
#    name: "{{ docker_rpms }}"
#    state: present
#  become: yes

# make sure a docker service is enabled and running (2/2)
#- name: make sure a docker service is enabled and running (2/2)
#  systemd:
#    name: docker
#    state: started
#    enabled: yes
#    masked: no
#  become: yes