# Tareas previas de configuración, estas tareas se han de realizar en todos los nodos.
# > Configuración de la sincronización horaria:
# timedatectl set-timezone Europe/Madrid
# dnf install chrony -y
# systemctl enable chronyd
# systemctl start chronyd
# timedatectl set-ntp true
# > Desativamos SELinux ya que no lo vamos a utilizar con kubernetes
# sed -i s/=enforcing/=disabled/g /etc/selinux/config
# > reboot?
# > Instalamos los siguientes paquetes:
# dnf install nfs-utils nfs4-acl-tools wget -y

- name: Preview task in all nodes (master and workers)
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all
  tasks:
    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
    - name: Set timezone to Europe/Madrid
      timezone:
        name: Europe/Madrid
