# Tareas previas de configuración, estas tareas se han de realizar en todos los nodos.

# Preview task in all nodes (master and workers)
- name: Preview task in all nodes (master and workers)
  gather_facts: false
  hosts: all
  tasks:

    # Set Timezone configuration to Europe/Madrid
    - name: Set timezone to Europe/Madrid
      timezone:
        name: Europe/Madrid

    # Install the latest version of Chrony package
    - name: Install the latest version of Chrony
      dnf:
        name: chrony
        state: latest
      become: yes

    # Make sure a chrony service unit is enabled and running
    - name: Make sure a chronyd service unit is enabled and running
      ansible.builtin.systemd:
        name: chronyd
        state: started        
        enabled: yes
      become: yes
    
    # Enable NTP (Network Time Protocol) to sync the system date/hour
    - name: Enable ntp
      command: /usr/bin/timedatectl set-ntp true
      become: yes

    # We discourage SELinux since we are not going to use it with kubernetes
    - name: Deactivate SELinux
      command: /usr/bin/sed -i s/=enforcing/=disabled/g /etc/selinux/config
      become: yes

    # Install the 'NFS (Network File System)' and 'wget' (Wget is a command-line utility for downloading files from the web) packages
    - name: Install the latest version of NFS (Network File System) and WGET packages
      dnf:
        name: 
          - nfs-utils
          - nfs4-acl-tools
          - wget
        state: present
      become: yes

    # Reboot machine with delay that might have lots of updates to apply
    - name: Reboot a slow machine that might have lots of updates to apply
      reboot:
      become: yes
