# Instalando la SDN, se realizará en master.local
# firewall-cmd --permanent --add-port=8285/udp
# firewall-cmd --permanent --add-port=8472/udp
# firewall-cmd --reload
# kubectl apply -f https://docs.projectcalico.org/manifests/canal.yaml

- name: install sdn
  hosts: master
  gather_facts: false
  vars_files:
    - "group_vars/sdn.yaml"
  roles:
    - sdn